CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app VARCHAR(512) NOT NULL,
    uri VARCHAR(512) NOT NULL,
    ip VARCHAR(512) NOT NULL,
    dateTime TIMESTAMP NOT NULL
);

